### ISSUE TITLE
prev & next with hotkeys/arrow keys?

### ISSUE THREAD

**Issue by deepestcarpet** [FiftyNine/SCPper#30]
e.g. for numbered pages, if i'm at scp 3313 and i press right arrow (or whatever), it goes to scp 3314. probably shouldnt apply to -Js because #10. or on forum pages, left arrow will go to the next page of a thread/discussions page if it isn't page 1 (that might be a bit much though).

**Comment by FiftyNine** [comment]
Hotkeys are always a touchy issue. Accidentally pressing a hotkey may result in an unexpected behaviour. There is a reason Chrome stopped using backspace as a hotkey to go to the previous page - users would press it, thinking some form had focus and instead go the previous page and lose state. This problem becomes even bigger in case of add-ons and plugins that alter default behaviour of a web page, because between the browser, web page and add-ons it would be even harder to track the issue. 
Thank you for the idea, but I think that consistent and predictable behaviour is more important.
